// Copyright 2015 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build ignore
// +build ignore

// Small program to generate roboto_regular.go and droid_sans_mono.go.
//
// TODO(crawshaw): italics, bold.
package font

//package main

import (
	"bytes"
	"compress/flate"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
	"net/http"
	"os"
)

var urls = map[string]string{
	"robotoRegular": "https://github.com/google/fonts/raw/master/apache/roboto/Roboto-Regular.ttf",
	"droidSansMono": "https://github.com/google/fonts/raw/master/apache/droidsansmono/DroidSansMono.ttf",
}

func write(name, url string) {
	resp, err := http.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	data, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("error reading %q: %v", url, err)
	}

	data, err = deflate(data)
	if err != nil {
		log.Fatalf("error deflating %q: %v", url, err)
	}

	buffer := new(bytes.Buffer)
	fmt.Fprint(buffer, "// GENERATED BY mkfont.go\n\n")
	fmt.Fprint(buffer, "package font\n\n")
	fmt.Fprintf(buffer, "var %s = []byte{\n", name)

	for len(data) > 0 {
		n := 16
		if n > len(data) {
			n = len(data)
		}

		for _, c := range data[:n] {
			fmt.Fprintf(buffer, "0x%02x,", c)
		}
		fmt.Fprintf(buffer, "\n")

		data = data[n:]
	}

	fmt.Fprint(buffer, "}")
	bufBytes := buffer.Bytes()

	formatted, err := format.Source(bufBytes)
	if err != nil {
		os.Stderr.Write(bufBytes)
		log.Fatalf("error formatting: %v", err)
	}

	file, err := os.Create(name + ".go")
	if err != nil {
		log.Fatal(err)
	}

	if _, err := file.Write(formatted); err != nil {
		log.Fatal(err)
	}

	if err := file.Close(); err != nil {
		log.Fatal(err)
	}
}

func main() {
	fmt.Println("generating fonts...")
	for name, url := range urls {
		write(name, url)
	}
}

func deflate(src []byte) ([]byte, error) {
	buf := new(bytes.Buffer)
	writer, err := flate.NewWriter(buf, flate.DefaultCompression)
	if err != nil {
		return nil, err
	}

	if _, err := writer.Write(src); err != nil {
		return nil, err
	}

	if err := writer.Close(); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
